// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvmleyuyqavunvmeirze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2bWxleXV5cWF2dW52bWVpcnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDAzMjIsImV4cCI6MjA2ODUxNjMyMn0.-lQm4oQjhhX8O0jfQia3SJR65IRHevw6l-ZbgnPSYqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});